"""Pydantic models for the AI Team MVP."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Shared / low-level models
# ---------------------------------------------------------------------------


class TaskStatus(str, Enum):
    """Lifecycle status of a single task."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    APPROVED = "approved"
    REJECTED = "rejected"
    APPROVED_AFTER_RETRY = "approved_after_retry"


class RunStatus(str, Enum):
    """Lifecycle status of a full orchestration run."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Core domain models
# ---------------------------------------------------------------------------


class Goal(BaseModel):
    """The original user goal/request that triggers a run."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    text: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Artifact(BaseModel):
    """A single output artifact produced by the Worker for a Task."""
    artifact_type: str = "text"  # e.g. "code", "markdown", "json"
    filename: Optional[str] = None
    content: str


class Task(BaseModel):
    """A single unit of work generated by the Planner and executed by the Worker."""
    task_id: str
    description: str
    dependencies: List[str] = Field(default_factory=list)
    context: Dict[str, Any] = Field(default_factory=dict)
    output: Optional[str] = None
    artifacts: List[Artifact] = Field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    attempts: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)


class TaskPlan(BaseModel):
    """The structured output produced by the Planner agent."""
    summary: str
    tasks: List[Task]
    execution_order: str = "sequential"  # "sequential" | "parallel" | "dag"


class WorkerResult(BaseModel):
    """Result returned by the Worker after executing a Task."""
    raw_output: str
    artifacts: List[Artifact] = Field(default_factory=list)
    self_assessment_confidence: float = 0.5
    self_assessment_notes: Optional[str] = None


class ReviewResult(BaseModel):
    """Result returned by the Reviewer after evaluating a Worker output."""
    is_valid: bool
    feedback: str
    issues: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    retry_allowed: bool = True
    score: float = 0.0


# ---------------------------------------------------------------------------
# Agent output wrappers
# ---------------------------------------------------------------------------


class PlannerOutput(BaseModel):
    """Wrapper around the raw Planner result with metadata."""
    raw_text: str
    tasks: List[Task] = Field(default_factory=list)
    plan_summary: str = ""


class WorkerOutput(BaseModel):
    """Wrapper around the raw Worker result with metadata."""
    raw_text: str
    task_id: str
    attempt: int = 1


class ReviewerOutput(BaseModel):
    """Wrapper around the raw Reviewer result with metadata."""
    raw_text: str
    is_valid: bool
    feedback: str
    task_id: str


# ---------------------------------------------------------------------------
# Run state (in‑memory for Milestone 1)
# ---------------------------------------------------------------------------


class RunState(BaseModel):
    """Mutable state maintained by the Orchestrator throughout a run.

    In Milestone 1 this lives in memory.  Future milestones persist it to a DB.
    """
    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: RunStatus = RunStatus.PENDING
    current_goal: Optional[Goal] = None
    planner_output: Optional[PlannerOutput] = None
    current_task: Optional[Task] = None
    total_tasks: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
