"""Planner Agent – decomposes a user goal into 3–7 sequential tasks."""

from __future__ import annotations

import json
from typing import Any, List

from pydantic import BaseModel, Field

from src.providers.base_provider import AbstractLLMProvider, ProviderResponse
from src.schemas.models import Goal, PlannerOutput, Task, TaskPlan
from src.utils.json_parser import _extract_and_parse_json


PLANNER_SCHEMA = {
    "type": "object",
    "properties": {
        "summary": {"type": "string"},
        "tasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                    "description": {"type": "string"},
                    "dependencies": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "context": {"type": "object"},
                },
                "required": ["task_id", "description", "dependencies", "context"],
            },
        },
        "execution_order": {"type": "string"},
    },
    "required": ["summary", "tasks", "execution_order"],
}


class PlannerAgent:
    """Agent that breaks down a high-level goal into an ordered list of tasks."""

    SYSTEM_PROMPT = """You are a **Planner Agent** in an AI team.
Your job is to take a user goal and break it down into 3–7 clear, actionable tasks.

OUTPUT FORMAT:
You MUST respond with ONLY a single JSON object that matches this exact schema (no exceptions):
{
  "summary": "Brief summary of the overall plan",
  "tasks": [
    {"task_id": "t1", "description": "Specific, actionable task description", "dependencies": [], "context": {}},
    {"task_id": "t2", "description": "Next task that may depend on t1", "dependencies": ["t1"], "context": {}},
    ...
  ],
  "execution_order": "sequential"
}

RULES:
- Generate EXACTLY 3 to 7 tasks (not less, not more).
- Tasks should be concrete and specific (not vague).
- Use sequential dependencies when one task needs another's output.
- Each task_id must be unique and follow pattern t1, t2, t3...
- DO NOT include any explanations, reasoning, markdown, code fences, or text before/after the JSON.
- Your entire response must be valid JSON that can be parsed directly.
"""

    def __init__(self, provider: AbstractLLMProvider) -> None:
        self.provider = provider

    async def execute(self, goal: str) -> PlannerOutput:
        """Run the planner on the given goal and return a structured plan."""
        prompt = f"User Goal:\n{goal}\n\nReturn the task plan as JSON."
        response: ProviderResponse = await self.provider.generate(
            system_prompt=self.SYSTEM_PROMPT,
            user_prompt=prompt,
            schema=PLANNER_SCHEMA,
        )

        plan = self._parse_plan(response.content)
        planner_out = PlannerOutput(
            raw_text=response.content,
            tasks=plan.tasks,
            plan_summary=plan.summary,
        )
        return planner_out

    def _parse_plan(self, raw_text: str) -> TaskPlan:
        """Parse and validate the provider's structured JSON plan."""
        data = _extract_and_parse_json(raw_text)

        # Validate required fields
        if "tasks" not in data or not isinstance(data["tasks"], list):
            raise ValueError("Planner output missing 'tasks' list")

        tasks: List[Task] = []
        for idx, t in enumerate(data["tasks"], 1):
            if not isinstance(t, dict):
                raise ValueError(f"Task {idx} is not an object")

            task_id = t.get("task_id", f"t{idx}")
            description = t.get("description", "").strip()
            if not description:
                raise ValueError(f"Task {idx} has empty description")

            dependencies = t.get("dependencies", [])
            if not isinstance(dependencies, list):
                dependencies = []

            context = t.get("context", {})
            if not isinstance(context, dict):
                context = {}

            tasks.append(
                Task(
                    task_id=task_id,
                    description=description,
                    dependencies=dependencies,
                    context=context,
                )
            )

        if len(tasks) < 3:
            raise ValueError(f"Planner produced only {len(tasks)} tasks (minimum 3)")
        if len(tasks) > 7:
            raise ValueError(f"Planner produced {len(tasks)} tasks (maximum 7)")

        summary = data.get("summary", "Plan generated by Planner Agent")

        return TaskPlan(
            summary=summary,
            tasks=tasks,
            execution_order=data.get("execution_order", "sequential"),
        )